import { ethers } from "hardhat";

async function main() {
  console.log("Starting deployment of We The People Governance Suite...");

  // 1. Deploy Voter Registry (The source of truth for ZK roots)
  const VoterRegistry = await ethers.getContractFactory("DistrictVoterRegistry");
  const registry = await VoterRegistry.deploy();
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log(`DistrictVoterRegistry deployed to: ${registryAddress}`);

  // 2. Deploy the ZK Verifier (Generated from snarkjs)
  // Note: This assumes Verifier.sol has been generated by the compile script
  const Verifier = await ethers.getContractFactory("Verifier");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddress = await verifier.getAddress();
  console.log(`ZK Verifier deployed to: ${verifierAddress}`);

  // 3. Deploy Polls Contract (Anonymous voting)
  const Polls = await ethers.getContractFactory("Polls");
  const polls = await Polls.deploy(registryAddress);
  await polls.waitForDeployment();
  console.log(`Polls contract deployed to: ${await polls.getAddress()}`);

  // 4. Deploy Instructions Contract (Verified constituent communication)
  const Instructions = await ethers.getContractFactory("Instructions");
  const instructions = await Instructions.deploy(registryAddress);
  await instructions.waitForDeployment();
  console.log(`Instructions contract deployed to: ${await instructions.getAddress()}`);

  console.log("Deployment complete. Governance suite is active.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
